version: '2'

services:
  homepage:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: [
      "./pkg/static:/usr/share/nginx/html",
      "./pkg/js:/app/js"
    ]
    ports: ["80:80"]
